# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/tercera-manoUI.ui'
#
# Created: Sat Sep 20 01:57:50 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(714, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.Asociacion_impedancias = QtGui.QWidget()
        self.Asociacion_impedancias.setObjectName("Asociacion_impedancias")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.Asociacion_impedancias)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_imp_text_1 = QtGui.QLabel(self.Asociacion_impedancias)
        self.label_imp_text_1.setObjectName("label_imp_text_1")
        self.horizontalLayout.addWidget(self.label_imp_text_1)
        self.lineEdit = QtGui.QLineEdit(self.Asociacion_impedancias)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_imp_2 = QtGui.QLabel(self.Asociacion_impedancias)
        self.label_imp_2.setObjectName("label_imp_2")
        self.horizontalLayout_2.addWidget(self.label_imp_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.Asociacion_impedancias)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.pushButton_asociacion_impedancias = QtGui.QPushButton(self.Asociacion_impedancias)
        self.pushButton_asociacion_impedancias.setObjectName("pushButton_asociacion_impedancias")
        self.verticalLayout_3.addWidget(self.pushButton_asociacion_impedancias)
        self.label_3 = QtGui.QLabel(self.Asociacion_impedancias)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.Asociacion_impedancias)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_8 = QtGui.QLabel(self.Asociacion_impedancias)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.Asociacion_impedancias, "")
        self.Calculo_impedancias = QtGui.QWidget()
        self.Calculo_impedancias.setEnabled(True)
        self.Calculo_impedancias.setObjectName("Calculo_impedancias")
        self.cB_cz = QtGui.QComboBox(self.Calculo_impedancias)
        self.cB_cz.setEnabled(True)
        self.cB_cz.setGeometry(QtCore.QRect(10, 10, 101, 22))
        self.cB_cz.setObjectName("cB_cz")
        self.cB_cz.addItem("")
        self.cB_cz.addItem("")
        self.lE_cz_val = QtGui.QLineEdit(self.Calculo_impedancias)
        self.lE_cz_val.setGeometry(QtCore.QRect(80, 40, 113, 21))
        self.lE_cz_val.setObjectName("lE_cz_val")
        self.label = QtGui.QLabel(self.Calculo_impedancias)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 50, 48, 13))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.Calculo_impedancias)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_2.setObjectName("label_2")
        self.lE_cz_freq = QtGui.QLineEdit(self.Calculo_impedancias)
        self.lE_cz_freq.setEnabled(True)
        self.lE_cz_freq.setGeometry(QtCore.QRect(80, 70, 113, 21))
        self.lE_cz_freq.setObjectName("lE_cz_freq")
        self.comboBox_3 = QtGui.QComboBox(self.Calculo_impedancias)
        self.comboBox_3.setEnabled(True)
        self.comboBox_3.setGeometry(QtCore.QRect(200, 40, 71, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.pushButton_calcula_impedancias = QtGui.QPushButton(self.Calculo_impedancias)
        self.pushButton_calcula_impedancias.setGeometry(QtCore.QRect(40, 130, 96, 31))
        self.pushButton_calcula_impedancias.setObjectName("pushButton_calcula_impedancias")
        self.lb_cz_sol = QtGui.QLabel(self.Calculo_impedancias)
        self.lb_cz_sol.setGeometry(QtCore.QRect(30, 190, 381, 21))
        self.lb_cz_sol.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard)
        self.lb_cz_sol.setObjectName("lb_cz_sol")
        self.tabWidget.addTab(self.Calculo_impedancias, "")
        self.Estrella_triangulo = QtGui.QWidget()
        self.Estrella_triangulo.setObjectName("Estrella_triangulo")
        self.lE_dt_1 = QtGui.QLineEdit(self.Estrella_triangulo)
        self.lE_dt_1.setGeometry(QtCore.QRect(10, 200, 113, 28))
        self.lE_dt_1.setObjectName("lE_dt_1")
        self.lE_dt_2 = QtGui.QLineEdit(self.Estrella_triangulo)
        self.lE_dt_2.setGeometry(QtCore.QRect(10, 230, 113, 28))
        self.lE_dt_2.setObjectName("lE_dt_2")
        self.lE_dt_3 = QtGui.QLineEdit(self.Estrella_triangulo)
        self.lE_dt_3.setGeometry(QtCore.QRect(10, 260, 113, 28))
        self.lE_dt_3.setObjectName("lE_dt_3")
        self.cB_dt = QtGui.QComboBox(self.Estrella_triangulo)
        self.cB_dt.setGeometry(QtCore.QRect(10, 170, 191, 28))
        self.cB_dt.setObjectName("cB_dt")
        self.cB_dt.addItem("")
        self.cB_dt.addItem("")
        self.lb_dt_1 = QtGui.QLabel(self.Estrella_triangulo)
        self.lb_dt_1.setGeometry(QtCore.QRect(140, 210, 101, 18))
        self.lb_dt_1.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lb_dt_1.setObjectName("lb_dt_1")
        self.lb_dt_2 = QtGui.QLabel(self.Estrella_triangulo)
        self.lb_dt_2.setGeometry(QtCore.QRect(140, 240, 101, 18))
        self.lb_dt_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lb_dt_2.setObjectName("lb_dt_2")
        self.lb_dt_3 = QtGui.QLabel(self.Estrella_triangulo)
        self.lb_dt_3.setGeometry(QtCore.QRect(140, 270, 101, 18))
        self.lb_dt_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.lb_dt_3.setObjectName("lb_dt_3")
        self.pB_dt_cal = QtGui.QPushButton(self.Estrella_triangulo)
        self.pB_dt_cal.setGeometry(QtCore.QRect(10, 290, 231, 28))
        self.pB_dt_cal.setObjectName("pB_dt_cal")
        self.lb_dt_picture = QtGui.QLabel(self.Estrella_triangulo)
        self.lb_dt_picture.setGeometry(QtCore.QRect(10, 10, 311, 141))
        self.lb_dt_picture.setMouseTracking(False)
        self.lb_dt_picture.setToolTip("")
        self.lb_dt_picture.setStatusTip("")
        self.lb_dt_picture.setText("")
        self.lb_dt_picture.setTextFormat(QtCore.Qt.AutoText)
        self.lb_dt_picture.setPixmap(QtGui.QPixmap("../img/estrella_triangulo.png"))
        self.lb_dt_picture.setScaledContents(True)
        self.lb_dt_picture.setWordWrap(True)
        self.lb_dt_picture.setObjectName("lb_dt_picture")
        self.tabWidget.addTab(self.Estrella_triangulo, "")
        self.IIntegrador = QtGui.QWidget()
        self.IIntegrador.setEnabled(True)
        self.IIntegrador.setObjectName("IIntegrador")
        self.verticalLayout = QtGui.QVBoxLayout(self.IIntegrador)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_int_funcion = QtGui.QLineEdit(self.IIntegrador)
        self.lineEdit_int_funcion.setObjectName("lineEdit_int_funcion")
        self.verticalLayout.addWidget(self.lineEdit_int_funcion)
        self.label_funcion = QtGui.QLabel(self.IIntegrador)
        self.label_funcion.setObjectName("label_funcion")
        self.verticalLayout.addWidget(self.label_funcion)
        self.radioButton_int_def = QtGui.QRadioButton(self.IIntegrador)
        self.radioButton_int_def.setObjectName("radioButton_int_def")
        self.verticalLayout.addWidget(self.radioButton_int_def)
        self.radioButton_int_indef = QtGui.QRadioButton(self.IIntegrador)
        self.radioButton_int_indef.setChecked(True)
        self.radioButton_int_indef.setObjectName("radioButton_int_indef")
        self.verticalLayout.addWidget(self.radioButton_int_indef)
        self.label_int_iteracion = QtGui.QLabel(self.IIntegrador)
        self.label_int_iteracion.setObjectName("label_int_iteracion")
        self.verticalLayout.addWidget(self.label_int_iteracion)
        self.spinBox_int = QtGui.QSpinBox(self.IIntegrador)
        self.spinBox_int.setMinimum(1)
        self.spinBox_int.setMaximum(3)
        self.spinBox_int.setObjectName("spinBox_int")
        self.verticalLayout.addWidget(self.spinBox_int)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_int_max_1 = QtGui.QLabel(self.IIntegrador)
        self.label_int_max_1.setObjectName("label_int_max_1")
        self.gridLayout.addWidget(self.label_int_max_1, 1, 4, 1, 1)
        self.lineEdit_int_max_2 = QtGui.QLineEdit(self.IIntegrador)
        self.lineEdit_int_max_2.setEnabled(False)
        self.lineEdit_int_max_2.setMaxLength(32)
        self.lineEdit_int_max_2.setObjectName("lineEdit_int_max_2")
        self.gridLayout.addWidget(self.lineEdit_int_max_2, 2, 5, 1, 1)
        self.label_int_max_2 = QtGui.QLabel(self.IIntegrador)
        self.label_int_max_2.setEnabled(False)
        self.label_int_max_2.setObjectName("label_int_max_2")
        self.gridLayout.addWidget(self.label_int_max_2, 2, 4, 1, 1)
        self.label_int_min_1 = QtGui.QLabel(self.IIntegrador)
        self.label_int_min_1.setObjectName("label_int_min_1")
        self.gridLayout.addWidget(self.label_int_min_1, 1, 2, 1, 1)
        self.lineEdit_int_var_3 = QtGui.QLineEdit(self.IIntegrador)
        self.lineEdit_int_var_3.setEnabled(False)
        self.lineEdit_int_var_3.setMaxLength(1)
        self.lineEdit_int_var_3.setObjectName("lineEdit_int_var_3")
        self.gridLayout.addWidget(self.lineEdit_int_var_3, 3, 1, 1, 1)
        self.lineEdit_int_min_1 = QtGui.QLineEdit(self.IIntegrador)
        self.lineEdit_int_min_1.setMaxLength(32)
        self.lineEdit_int_min_1.setObjectName("lineEdit_int_min_1")
        self.gridLayout.addWidget(self.lineEdit_int_min_1, 1, 3, 1, 1)
        self.lineEdit_int_var_1 = QtGui.QLineEdit(self.IIntegrador)
        self.lineEdit_int_var_1.setMaxLength(1)
        self.lineEdit_int_var_1.setObjectName("lineEdit_int_var_1")
        self.gridLayout.addWidget(self.lineEdit_int_var_1, 1, 1, 1, 1)
        self.label_int_text_3 = QtGui.QLabel(self.IIntegrador)
        self.label_int_text_3.setEnabled(False)
        self.label_int_text_3.setObjectName("label_int_text_3")
        self.gridLayout.addWidget(self.label_int_text_3, 3, 0, 1, 1)
        self.lineEdit_int_var_2 = QtGui.QLineEdit(self.IIntegrador)
        self.lineEdit_int_var_2.setEnabled(False)
        self.lineEdit_int_var_2.setMaxLength(1)
        self.lineEdit_int_var_2.setObjectName("lineEdit_int_var_2")
        self.gridLayout.addWidget(self.lineEdit_int_var_2, 2, 1, 1, 1)
        self.label_int_min_2 = QtGui.QLabel(self.IIntegrador)
        self.label_int_min_2.setEnabled(False)
        self.label_int_min_2.setObjectName("label_int_min_2")
        self.gridLayout.addWidget(self.label_int_min_2, 2, 2, 1, 1)
        self.label_int_min_3 = QtGui.QLabel(self.IIntegrador)
        self.label_int_min_3.setEnabled(False)
        self.label_int_min_3.setObjectName("label_int_min_3")
        self.gridLayout.addWidget(self.label_int_min_3, 3, 2, 1, 1)
        self.lineEdit_int_max_1 = QtGui.QLineEdit(self.IIntegrador)
        self.lineEdit_int_max_1.setMaxLength(32)
        self.lineEdit_int_max_1.setObjectName("lineEdit_int_max_1")
        self.gridLayout.addWidget(self.lineEdit_int_max_1, 1, 5, 1, 1)
        self.label_int_text_2 = QtGui.QLabel(self.IIntegrador)
        self.label_int_text_2.setEnabled(False)
        self.label_int_text_2.setObjectName("label_int_text_2")
        self.gridLayout.addWidget(self.label_int_text_2, 2, 0, 1, 1)
        self.label_int_text_1 = QtGui.QLabel(self.IIntegrador)
        self.label_int_text_1.setObjectName("label_int_text_1")
        self.gridLayout.addWidget(self.label_int_text_1, 1, 0, 1, 1)
        self.label_int_max_3 = QtGui.QLabel(self.IIntegrador)
        self.label_int_max_3.setEnabled(False)
        self.label_int_max_3.setObjectName("label_int_max_3")
        self.gridLayout.addWidget(self.label_int_max_3, 3, 4, 1, 1)
        self.lineEdit_int_max_3 = QtGui.QLineEdit(self.IIntegrador)
        self.lineEdit_int_max_3.setEnabled(False)
        self.lineEdit_int_max_3.setMaxLength(32)
        self.lineEdit_int_max_3.setObjectName("lineEdit_int_max_3")
        self.gridLayout.addWidget(self.lineEdit_int_max_3, 3, 5, 1, 1)
        self.lineEdit_int_min_2 = QtGui.QLineEdit(self.IIntegrador)
        self.lineEdit_int_min_2.setEnabled(False)
        self.lineEdit_int_min_2.setMaxLength(32)
        self.lineEdit_int_min_2.setObjectName("lineEdit_int_min_2")
        self.gridLayout.addWidget(self.lineEdit_int_min_2, 2, 3, 1, 1)
        self.lineEdit_int_min_3 = QtGui.QLineEdit(self.IIntegrador)
        self.lineEdit_int_min_3.setEnabled(False)
        self.lineEdit_int_min_3.setMaxLength(32)
        self.lineEdit_int_min_3.setObjectName("lineEdit_int_min_3")
        self.gridLayout.addWidget(self.lineEdit_int_min_3, 3, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.splitter = QtGui.QSplitter(self.IIntegrador)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_integra = QtGui.QPushButton(self.splitter)
        self.pushButton_integra.setObjectName("pushButton_integra")
        self.pushButton_deriva = QtGui.QPushButton(self.splitter)
        self.pushButton_deriva.setObjectName("pushButton_deriva")
        self.verticalLayout.addWidget(self.splitter)
        self.label_int_solucion = QtGui.QLabel(self.IIntegrador)
        self.label_int_solucion.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_int_solucion.setObjectName("label_int_solucion")
        self.verticalLayout.addWidget(self.label_int_solucion)
        self.tabWidget.addTab(self.IIntegrador, "")
        self.MOSFET = QtGui.QWidget()
        self.MOSFET.setEnabled(True)
        self.MOSFET.setObjectName("MOSFET")
        self.radioButton = QtGui.QRadioButton(self.MOSFET)
        self.radioButton.setEnabled(False)
        self.radioButton.setGeometry(QtCore.QRect(20, 10, 109, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtGui.QRadioButton(self.MOSFET)
        self.radioButton_2.setEnabled(False)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 30, 109, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton = QtGui.QPushButton(self.MOSFET)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(220, 260, 93, 27))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_3 = QtGui.QLineEdit(self.MOSFET)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 80, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtGui.QLineEdit(self.MOSFET)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 110, 113, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtGui.QLineEdit(self.MOSFET)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QtCore.QRect(70, 140, 113, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_8 = QtGui.QLineEdit(self.MOSFET)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setGeometry(QtCore.QRect(70, 170, 113, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.comboBox = QtGui.QComboBox(self.MOSFET)
        self.comboBox.setEnabled(False)
        self.comboBox.setGeometry(QtCore.QRect(80, 50, 85, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtGui.QLabel(self.MOSFET)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 62, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.MOSFET)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 62, 15))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.MOSFET)
        self.label_7.setEnabled(False)
        self.label_7.setGeometry(QtCore.QRect(20, 150, 62, 15))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtGui.QLabel(self.MOSFET)
        self.label_9.setEnabled(False)
        self.label_9.setGeometry(QtCore.QRect(20, 180, 62, 15))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.MOSFET, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 714, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAsociaci_n_de_impedancias = QtGui.QAction(MainWindow)
        self.actionAsociaci_n_de_impedancias.setEnabled(False)
        self.actionAsociaci_n_de_impedancias.setObjectName("actionAsociaci_n_de_impedancias")
        self.actionC_lculo_de_impedancias = QtGui.QAction(MainWindow)
        self.actionC_lculo_de_impedancias.setEnabled(False)
        self.actionC_lculo_de_impedancias.setObjectName("actionC_lculo_de_impedancias")
        self.actionConversor_estrella_tri_ngulo = QtGui.QAction(MainWindow)
        self.actionConversor_estrella_tri_ngulo.setEnabled(False)
        self.actionConversor_estrella_tri_ngulo.setObjectName("actionConversor_estrella_tri_ngulo")
        self.actionIntegrador = QtGui.QAction(MainWindow)
        self.actionIntegrador.setEnabled(False)
        self.actionIntegrador.setObjectName("actionIntegrador")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAyuda = QtGui.QAction(MainWindow)
        self.actionAyuda.setObjectName("actionAyuda")
        self.menuFile.addAction(self.actionAsociaci_n_de_impedancias)
        self.menuFile.addAction(self.actionC_lculo_de_impedancias)
        self.menuFile.addAction(self.actionConversor_estrella_tri_ngulo)
        self.menuFile.addAction(self.actionIntegrador)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAyuda)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_int_max_3, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.pushButton_asociacion_impedancias)
        MainWindow.setTabOrder(self.pushButton_asociacion_impedancias, self.pushButton_integra)
        MainWindow.setTabOrder(self.pushButton_integra, self.cB_cz)
        MainWindow.setTabOrder(self.cB_cz, self.lE_cz_val)
        MainWindow.setTabOrder(self.lE_cz_val, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.lE_cz_freq)
        MainWindow.setTabOrder(self.lE_cz_freq, self.pushButton_deriva)
        MainWindow.setTabOrder(self.pushButton_deriva, self.cB_dt)
        MainWindow.setTabOrder(self.cB_dt, self.lE_dt_1)
        MainWindow.setTabOrder(self.lE_dt_1, self.lE_dt_2)
        MainWindow.setTabOrder(self.lE_dt_2, self.lE_dt_3)
        MainWindow.setTabOrder(self.lE_dt_3, self.pB_dt_cal)
        MainWindow.setTabOrder(self.pB_dt_cal, self.lineEdit_int_funcion)
        MainWindow.setTabOrder(self.lineEdit_int_funcion, self.radioButton_int_def)
        MainWindow.setTabOrder(self.radioButton_int_def, self.radioButton_int_indef)
        MainWindow.setTabOrder(self.radioButton_int_indef, self.lineEdit_int_var_1)
        MainWindow.setTabOrder(self.lineEdit_int_var_1, self.lineEdit_int_min_1)
        MainWindow.setTabOrder(self.lineEdit_int_min_1, self.lineEdit_int_max_1)
        MainWindow.setTabOrder(self.lineEdit_int_max_1, self.lineEdit_int_var_2)
        MainWindow.setTabOrder(self.lineEdit_int_var_2, self.lineEdit_int_min_2)
        MainWindow.setTabOrder(self.lineEdit_int_min_2, self.lineEdit_int_max_2)
        MainWindow.setTabOrder(self.lineEdit_int_max_2, self.lineEdit_int_var_3)
        MainWindow.setTabOrder(self.lineEdit_int_var_3, self.lineEdit_int_min_3)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tercera Mano", None, QtGui.QApplication.UnicodeUTF8))
        self.label_imp_text_1.setText(QtGui.QApplication.translate("MainWindow", "Insert value: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_imp_2.setText(QtGui.QApplication.translate("MainWindow", "Insert value: ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_asociacion_impedancias.setText(QtGui.QApplication.translate("MainWindow", "Calcular", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Valor serie:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Valor paralelo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Valor suma cuadrática:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Asociacion_impedancias), QtGui.QApplication.translate("MainWindow", "Asociación de impedancias", None, QtGui.QApplication.UnicodeUTF8))
        self.cB_cz.setItemText(0, QtGui.QApplication.translate("MainWindow", "Condensador", None, QtGui.QApplication.UnicodeUTF8))
        self.cB_cz.setItemText(1, QtGui.QApplication.translate("MainWindow", "Bobina", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Valor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Frecuencia:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_calcula_impedancias.setText(QtGui.QApplication.translate("MainWindow", "Calcula", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_cz_sol.setText(QtGui.QApplication.translate("MainWindow", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Calculo_impedancias), QtGui.QApplication.translate("MainWindow", "Cálculo de impedancias", None, QtGui.QApplication.UnicodeUTF8))
        self.cB_dt.setItemText(0, QtGui.QApplication.translate("MainWindow", "Estrella -> Triángulo", None, QtGui.QApplication.UnicodeUTF8))
        self.cB_dt.setItemText(1, QtGui.QApplication.translate("MainWindow", "Triángulo -> Estrella", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_dt_1.setText(QtGui.QApplication.translate("MainWindow", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_dt_2.setText(QtGui.QApplication.translate("MainWindow", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_dt_3.setText(QtGui.QApplication.translate("MainWindow", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.pB_dt_cal.setText(QtGui.QApplication.translate("MainWindow", "Calcular", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Estrella_triangulo), QtGui.QApplication.translate("MainWindow", "Conversor estrella:triángulo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_funcion.setText(QtGui.QApplication.translate("MainWindow", "Función: ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_int_def.setText(QtGui.QApplication.translate("MainWindow", "Definida", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_int_indef.setText(QtGui.QApplication.translate("MainWindow", "Indefinida", None, QtGui.QApplication.UnicodeUTF8))
        self.label_int_iteracion.setText(QtGui.QApplication.translate("MainWindow", "Iteraciones: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_int_max_1.setText(QtGui.QApplication.translate("MainWindow", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_int_max_2.setText(QtGui.QApplication.translate("MainWindow", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_int_min_1.setText(QtGui.QApplication.translate("MainWindow", "Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_int_var_3.setText(QtGui.QApplication.translate("MainWindow", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_int_var_1.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_int_text_3.setText(QtGui.QApplication.translate("MainWindow", "Integrar o derivar en: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_int_var_2.setText(QtGui.QApplication.translate("MainWindow", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_int_min_2.setText(QtGui.QApplication.translate("MainWindow", "Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_int_min_3.setText(QtGui.QApplication.translate("MainWindow", "Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_int_text_2.setText(QtGui.QApplication.translate("MainWindow", "Integrar o derivar en: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_int_text_1.setText(QtGui.QApplication.translate("MainWindow", "Integrar o derivar en: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_int_max_3.setText(QtGui.QApplication.translate("MainWindow", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_integra.setText(QtGui.QApplication.translate("MainWindow", "Integrar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_deriva.setText(QtGui.QApplication.translate("MainWindow", "Derivar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_int_solucion.setText(QtGui.QApplication.translate("MainWindow", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IIntegrador), QtGui.QApplication.translate("MainWindow", "Integrador", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "NMOS", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "PMOS", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "VD", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "VS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "VG", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Id", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "VD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "VS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "VG", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MOSFET), QtGui.QApplication.translate("MainWindow", "MOSFET", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAsociaci_n_de_impedancias.setText(QtGui.QApplication.translate("MainWindow", "Asociación de impedancias", None, QtGui.QApplication.UnicodeUTF8))
        self.actionC_lculo_de_impedancias.setText(QtGui.QApplication.translate("MainWindow", "Cálculo de impedancias", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConversor_estrella_tri_ngulo.setText(QtGui.QApplication.translate("MainWindow", "Conversor estrella:triángulo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIntegrador.setText(QtGui.QApplication.translate("MainWindow", "Integrador", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAyuda.setText(QtGui.QApplication.translate("MainWindow", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))

